### ISSUE TITLE
Unable to run Hapiest

### ISSUE THREAD

**Issue by sourabhk419** [hitranonline/hapiest#48] opened 2020-03-29 20:23 UTC
Hello everyone here,
I have been successful in installing all the packages as per the steps mentioned in the manual. I could also run the /src. I entered the API and I got exited from Hapiest. But I am unable to access the GUI.
The last step in the manual: "After you install hapiest, you can start it by calling run in a command prompt or terminal." i am unable to execute (not understanding what needs to be done). I have attached a snapshot of what I did and the error I am getting.
![image](https://user-images.githubusercontent.com/58051759/77859808-c09ddf80-720b-11ea-9e79-eda2215b7cca.png)
Can someone explain to me how it needs to be done?
Thank You in advance.

Regards!

**Comment by jkarns275** [comment] 2020-03-30 02:06
What happens when you run `py src` or `python3 src`? That is supposed to open the main GUI. If it doesn't open when you run that command I would at least expect an error of some kind...

**Comment by sourabhk419** [comment] 2020-03-30 06:16
So when I run py src I get the message to enter the API key.
![image](https://user-images.githubusercontent.com/58051759/77881123-8ad61680-725e-11ea-806e-2945f7f912b2.png)
When I enter the API key I get the following message.
![image](https://user-images.githubusercontent.com/58051759/77881189-b5c06a80-725e-11ea-9065-324e1c308c0c.png)
This goes on repeating but the GUI doesn't open.

Thank You.

**Comment by jkarns275** [comment] 2020-03-30 12:47
Looks like there was a change to the hapi API on the side of hitran.org - I'll have to contact Roman to see how I can fix this. That said, this software isn't currently being actively maintained so don't hold your breath.

**Comment by sourabhk419** [comment] 2020-03-30 12:52
Hi,
Thanks for getting back to me.
It would be nice to get this going as soon as possible. I want to simulate
some spectroscopic data for my simulations.
Nevertheless, if this is not working can you explain to me how is
absorption coefficient spectrum calculated from line by line spectrum? Also
I would like to know the absorption spectrum calculation. For what
concentration of particular molecule it is being calculated.

Thank you in advance.

Regards
Sourabh

**Comment by jkarns275** [comment] 2020-03-30 13:24
So, HAPIEST is based on a python api called HAPI. It is an open source python library that isn't too difficult to use. If you want to read about how HAPI works I believe this paper may answer some of your questions https://www.sciencedirect.com/science/article/abs/pii/S0022407315302466?via%3Dihub

I am not a spectroscopist myself, rather just a computer programmer, so I will probably not be able to answer your questions myself. 

If you would like to try using this HAPI API yourself, the manual is located here https://hitran.org/static/hapi/hapi_manual.pdf

That said, I just sent out an email to Roman, the author of HAPI. I'm sure he will get back to me soon and I can get this software up running within a few days. Once I have implemented a fix for this issue I will close it and you will probably receive an email notification.

**Comment by sourabhk419** [comment] 2020-04-01 08:50
Hi Josh,
thanks for your reply. I will go through the paper. meanwhile, could you
please send me the contact for Roman?
I would like to contact him regarding some technical queries about the
calculations.

Thanks

**Comment by jkarns275** [comment] 2020-04-01 14:09
You can find his email in either of the documents I linked.

**Comment by hitranonline** [comment] 2020-04-06 14:09
Dear Sourabh,

The web API problem was caused by upgrading to the new version of Django. We have fixed the url bug so feel free to try once again with HAPIEST. Please let know in case of other problems with the software.

Best wished,
Roman

**Comment by jkarns275** [comment] 2020-04-06 19:45
Thank you Roman!

I've tested it on my machine and this fix seems to have worked, so I will close this issue.

**Closed by jkarns275** 2020-04-06 19:45 UTC
